# Generated by Django 4.2 on 2025-04-04 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={},
        ),
        migrations.RemoveField(
            model_name='field',
            name='area_ha',
        ),
        migrations.RemoveField(
            model_name='field',
            name='boundary_geojson',
        ),
        migrations.RemoveField(
            model_name='field',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='field',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='field',
            name='organic_matter',
        ),
        migrations.RemoveField(
            model_name='field',
            name='soil_ph',
        ),
        migrations.AddField(
            model_name='field',
            name='crop_type',
            field=models.CharField(choices=[('maize', 'Maize'), ('soybean', 'Soybean')], default='maize', max_length=20),
        ),
        migrations.AddField(
            model_name='field',
            name='planting_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Planting Date'),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_type',
            field=models.CharField(choices=[('clay', 'Clay'), ('loam', 'Loam')], default='loam', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
