# Generated by Django 4.2 on 2025-04-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_alter_field_options_remove_field_area_ha_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='FarmField',
        ),
    ]
