# Generated by Django 4.2 on 2025-04-04 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0003_rename_field_farmfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irrigationadvisory',
            options={},
        ),
        migrations.RemoveField(
            model_name='irrigationadvisory',
            name='et0',
        ),
        migrations.RemoveField(
            model_name='irrigationadvisory',
            name='rainfall_predicted',
        ),
        migrations.RemoveField(
            model_name='irrigationadvisory',
            name='soil_moisture',
        ),
        migrations.RemoveField(
            model_name='irrigationadvisory',
            name='water_requirement',
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='crop_stage',
            field=models.CharField(default='Initial', max_length=50),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='eto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='rainfall',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='water_deficit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='water_need',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='irrigationadvisory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='irrigationadvisory',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.farmfield'),
        ),
        migrations.AlterField(
            model_name='irrigationadvisory',
            name='kc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='irrigationadvisory',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
