# Generated by Django 4.2 on 2025-07-22 16:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0004_alter_irrigationadvisory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmfield',
            options={'ordering': ['-created_at'], 'verbose_name': 'Farm Field', 'verbose_name_plural': 'Farm Fields'},
        ),
        migrations.AlterModelOptions(
            name='irrigationadvisory',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Irrigation Advisory', 'verbose_name_plural': 'Irrigation Advisories'},
        ),
        migrations.AddField(
            model_name='farmfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmfield',
            name='elevation',
            field=models.FloatField(blank=True, help_text='Field elevation in meters', null=True, verbose_name='Elevation (m)'),
        ),
        migrations.AddField(
            model_name='farmfield',
            name='field_area_ha',
            field=models.FloatField(blank=True, help_text='Field area in hectares', null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1000.0)], verbose_name='Field Area (ha)'),
        ),
        migrations.AddField(
            model_name='farmfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Confidence in recommendation (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='data_source',
            field=models.CharField(default='simulated', help_text='Source of weather data (GEE, API, simulated)', max_length=50),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='irrigation_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='irrigation_volume',
            field=models.FloatField(default=0.0, help_text='Recommended irrigation volume in mm'),
        ),
        migrations.AddField(
            model_name='irrigationadvisory',
            name='soil_moisture',
            field=models.FloatField(default=0.0, help_text='Soil moisture percentage'),
        ),
        migrations.AlterField(
            model_name='farmfield',
            name='crop_type',
            field=models.CharField(choices=[('maize', 'Maize'), ('soybean', 'Soybean'), ('rice', 'Rice'), ('wheat', 'Wheat'), ('sugarcane', 'Sugarcane'), ('cotton', 'Cotton'), ('beans', 'Beans'), ('potatoes', 'Potatoes'), ('tomatoes', 'Tomatoes'), ('cassava', 'Cassava')], default='maize', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmfield',
            name='soil_type',
            field=models.CharField(choices=[('clay', 'Clay'), ('loam', 'Loam'), ('sandy', 'Sandy'), ('silt', 'Silt'), ('clay_loam', 'Clay Loam'), ('sandy_loam', 'Sandy Loam')], default='loam', max_length=20),
        ),
    ]
