# Generated by Django 4.2 on 2025-07-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0005_alter_farmfield_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationadvisory',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='advisory.farmfield'),
        ),
    ]
