# Generated by Django 4.2 on 2025-08-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0006_alter_irrigationadvisory_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfield',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('clay', 'Clay'), ('loam', 'Loam'), ('sandy', 'Sandy'), ('silt', 'Silt'), ('clay_loam', 'Clay Loam'), ('sandy_loam', 'Sandy Loam')], default='loam', max_length=20, null=True),
        ),
    ]
