# Generated by Django 4.2 on 2025-08-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0007_alter_farmfield_soil_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_api_key', models.CharField(blank=True, help_text='API key for weather data service', max_length=200)),
                ('weather_api_provider', models.CharField(choices=[('openweathermap', 'OpenWeatherMap'), ('weatherapi', 'WeatherAPI'), ('custom', 'Custom API')], default='openweathermap', max_length=50)),
                ('gee_service_account_key', models.TextField(blank=True, help_text='JSON service account key for Google Earth Engine')),
                ('gee_project_id', models.CharField(blank=True, help_text='Google Cloud Project ID for Earth Engine', max_length=100)),
                ('default_crop_coefficient', models.FloatField(default=1.0, help_text='Default crop coefficient when specific data unavailable')),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Minimum confidence score for high-quality recommendations')),
                ('max_field_area', models.FloatField(default=1000.0, help_text='Maximum allowed field area in hectares')),
                ('enable_email_notifications', models.BooleanField(default=False, help_text='Enable email notifications for irrigation alerts')),
                ('notification_email', models.EmailField(blank=True, help_text='Email address for system notifications', max_length=254)),
                ('advisory_retention_days', models.IntegerField(default=365, help_text='Number of days to retain advisory records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
